# Generated by Django 5.2.17 on 2026-09-16 19:14

import apps.core.models
import django.db.models.deletion
import spectrum.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.FileField(blank=True, max_length=255, storage=spectrum.storages.private_storage, upload_to=apps.core.models.original_upload_to, validators=[apps.core.models.validate_image_extension], verbose_name='image')),
                ('web', models.FileField(blank=True, editable=False, max_length=255, storage=spectrum.storages.public_storage, upload_to='')),
                ('thumb', models.FileField(blank=True, editable=False, max_length=255, storage=spectrum.storages.public_storage, upload_to='')),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('image_status', models.CharField(choices=[('empty', 'No image'), ('pending', 'Waiting'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='empty', editable=False, max_length=12, verbose_name='image')),
                ('image_error', models.TextField(blank=True, editable=False)),
                ('slug', models.SlugField(help_text='Short id used in links, e.g. dps.', unique=True)),
                ('name', models.CharField(max_length=160)),
                ('short', models.CharField(blank=True, help_text='Shown under the round photo.', max_length=80, verbose_name='short name')),
                ('city', models.CharField(blank=True, max_length=80)),
                ('kind', models.CharField(choices=[('school', 'School'), ('college', 'College')], default='school', max_length=10, verbose_name='type')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.FileField(blank=True, max_length=255, storage=spectrum.storages.private_storage, upload_to=apps.core.models.original_upload_to, validators=[apps.core.models.validate_image_extension], verbose_name='image')),
                ('web', models.FileField(blank=True, editable=False, max_length=255, storage=spectrum.storages.public_storage, upload_to='')),
                ('thumb', models.FileField(blank=True, editable=False, max_length=255, storage=spectrum.storages.public_storage, upload_to='')),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('image_status', models.CharField(choices=[('empty', 'No image'), ('pending', 'Waiting'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='empty', editable=False, max_length=12, verbose_name='image')),
                ('image_error', models.TextField(blank=True, editable=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('date', models.DateField(blank=True, null=True)),
                ('date_label', models.CharField(blank=True, help_text='Optional display text. Blank shows the date, e.g. "March 15, 2025".', max_length=60)),
                ('price_per_photo', models.PositiveIntegerField(default=29, verbose_name='price per photo (₹)')),
                ('bundle_price', models.PositiveIntegerField(default=299, verbose_name='full album price (₹)')),
                ('is_recent', models.BooleanField(default=False, verbose_name='tag: recent')),
                ('is_popular', models.BooleanField(default=False, verbose_name='tag: popular')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='catalog.institution')),
            ],
            options={
                'ordering': ['sort_order', '-date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.FileField(blank=True, max_length=255, storage=spectrum.storages.private_storage, upload_to=apps.core.models.original_upload_to, validators=[apps.core.models.validate_image_extension], verbose_name='image')),
                ('web', models.FileField(blank=True, editable=False, max_length=255, storage=spectrum.storages.public_storage, upload_to='')),
                ('thumb', models.FileField(blank=True, editable=False, max_length=255, storage=spectrum.storages.public_storage, upload_to='')),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('image_status', models.CharField(choices=[('empty', 'No image'), ('pending', 'Waiting'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='empty', editable=False, max_length=12, verbose_name='image')),
                ('image_error', models.TextField(blank=True, editable=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('preview', models.FileField(blank=True, editable=False, max_length=255, storage=spectrum.storages.public_storage, upload_to='')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.event')),
            ],
            options={
                'verbose_name': 'event photo',
                'ordering': ['sort_order', 'pk'],
                'indexes': [models.Index(fields=['event', 'image_status', 'sort_order'], name='catalog_eve_event_i_b3ed4f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_published', 'sort_order'], name='catalog_eve_is_publ_afa2d5_idx'),
        ),
    ]
