# Generated by Django 6.0.6 on 2026-10-03 07:50

import apps.catalog.models
import apps.core.models
import django.db.models.deletion
import spectrum.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_institution_kind_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="price_per_video",
            field=models.PositiveIntegerField(
                default=199, verbose_name="price per video (₹)"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="bundle_price",
            field=models.PositiveIntegerField(
                default=299,
                help_text="All photos. Videos are priced per video on top.",
                verbose_name="full album price (₹)",
            ),
        ),
        migrations.CreateModel(
            name="EventVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        storage=spectrum.storages.private_storage,
                        upload_to=apps.core.models.original_upload_to,
                        validators=[apps.core.models.validate_image_extension],
                        verbose_name="image",
                    ),
                ),
                (
                    "web",
                    models.FileField(
                        blank=True,
                        editable=False,
                        max_length=255,
                        storage=spectrum.storages.public_storage,
                        upload_to="",
                    ),
                ),
                (
                    "thumb",
                    models.FileField(
                        blank=True,
                        editable=False,
                        max_length=255,
                        storage=spectrum.storages.public_storage,
                        upload_to="",
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "height",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "image_status",
                    models.CharField(
                        choices=[
                            ("empty", "No image"),
                            ("pending", "Waiting"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="empty",
                        editable=False,
                        max_length=12,
                        verbose_name="image",
                    ),
                ),
                ("image_error", models.TextField(blank=True, editable=False)),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "video",
                    models.FileField(
                        max_length=255,
                        storage=spectrum.storages.private_storage,
                        upload_to=apps.catalog.models.video_upload_to,
                        validators=[apps.catalog.models.validate_video_extension],
                        verbose_name="video file",
                    ),
                ),
                (
                    "duration_label",
                    models.CharField(
                        blank=True,
                        help_text='Shown on the card, e.g. "2:41".',
                        max_length=20,
                        verbose_name="duration",
                    ),
                ),
                (
                    "preview",
                    models.FileField(
                        blank=True,
                        editable=False,
                        max_length=255,
                        storage=spectrum.storages.public_storage,
                        upload_to="",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="catalog.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "event video",
                "ordering": ["sort_order", "pk"],
                "indexes": [
                    models.Index(
                        fields=["event", "sort_order"],
                        name="catalog_eve_event_i_fae4e3_idx",
                    )
                ],
            },
        ),
    ]
