# Generated by Django 5.2.17 on 2026-10-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_event_price_per_video_alter_event_bundle_price_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventphoto",
            options={
                "ordering": ["sort_order", "pk"],
                "verbose_name": "event photo",
                "verbose_name_plural": "all photos",
            },
        ),
    ]
