# Generated by Django 5.2.17 on 2026-10-09 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_institution_portal_login"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="institutionkind",
            options={"ordering": ["sort_order", "name"], "verbose_name": "type"},
        ),
    ]
