# Generated by Django 5.2.17 on 2026-10-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_institution_portal_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='not_for_sale',
            field=models.BooleanField(default=False, help_text="The gallery shows as usual, but checkout only says these photographs aren't for sale (Gallery & checkout pages › Not for sale message), and no order can be placed.", verbose_name='not for sale'),
        ),
    ]
