# Generated by Django 5.2.17 on 2026-09-16 19:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('args', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('run_after', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'background task',
                'ordering': ['run_after', 'id'],
                'indexes': [models.Index(fields=['status', 'run_after'], name='core_task_status_612c52_idx')],
            },
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.CharField(max_length=60)),
                ('parent_id', models.PositiveBigIntegerField(null=True)),
                ('base_sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadBatchFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=64)),
                ('object_id', models.PositiveBigIntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.uploadbatch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('batch', 'client_id'), name='uniq_batch_client')],
            },
        ),
    ]
