# Generated by Django 5.2.17 on 2026-09-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='prepared_keys',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
