# Generated by Django 5.2.17 on 2026-10-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_upload_prepared_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatchfile',
            name='created',
            field=models.BooleanField(default=True),
        ),
    ]
