# Generated by Django 5.2.17 on 2026-09-16 19:14

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
import spectrum.storages
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('institution', 'Institution'), ('spectrum', 'Spectrum team')], default='institution', max_length=12)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('token_version', models.PositiveIntegerField(default=1, editable=False)),
                ('institution', models.ForeignKey(blank=True, help_text='Leave blank for Spectrum team logins, which can see every institution.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='catalog.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'portal login',
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "6C" or "Nursery".', max_length=20)),
                ('slug', models.SlugField(blank=True, help_text='Filled from the name.', max_length=30)),
                ('group', models.CharField(choices=[('Primary', 'Primary'), ('Middle', 'Middle'), ('Senior', 'Senior')], default='Primary', max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='catalog.institution')),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
                'ordering': ['institution', 'sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.FileField(blank=True, max_length=255, storage=spectrum.storages.private_storage, upload_to=apps.core.models.original_upload_to, validators=[apps.core.models.validate_image_extension], verbose_name='image')),
                ('web', models.FileField(blank=True, editable=False, max_length=255, storage=spectrum.storages.public_storage, upload_to='')),
                ('thumb', models.FileField(blank=True, editable=False, max_length=255, storage=spectrum.storages.public_storage, upload_to='')),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('image_status', models.CharField(choices=[('empty', 'No image'), ('pending', 'Waiting'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='empty', editable=False, max_length=12, verbose_name='image')),
                ('image_error', models.TextField(blank=True, editable=False)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='portal.schoolclass', verbose_name='class')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CaptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.FileField(blank=True, max_length=255, storage=spectrum.storages.private_storage, upload_to=apps.core.models.original_upload_to, validators=[apps.core.models.validate_image_extension], verbose_name='image')),
                ('web', models.FileField(blank=True, editable=False, max_length=255, storage=spectrum.storages.public_storage, upload_to='')),
                ('thumb', models.FileField(blank=True, editable=False, max_length=255, storage=spectrum.storages.public_storage, upload_to='')),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('image_status', models.CharField(choices=[('empty', 'No image'), ('pending', 'Waiting'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='empty', editable=False, max_length=12, verbose_name='image')),
                ('image_error', models.TextField(blank=True, editable=False)),
                ('moment_title', models.CharField(blank=True, max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('correction', models.TextField(blank=True, help_text="The institution's correction note.")),
                ('requested', models.CharField(choices=[('needs-caption', 'Needs Caption'), ('needs-approval', 'Needs Approval'), ('needs-correction', 'Needs Correction')], default='needs-approval', max_length=20)),
                ('status', models.CharField(choices=[('needs-caption', 'Needs Caption'), ('needs-approval', 'Needs Approval'), ('needs-correction', 'Needs Correction'), ('approved', 'Approved'), ('corrected', 'Corrected')], db_index=True, default='needs-approval', max_length=20)),
                ('action_by', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caption_items', to='catalog.event')),
                ('institution', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='caption_items', to='catalog.institution')),
            ],
            options={
                'verbose_name': 'caption item',
                'ordering': ['sort_order', 'pk'],
                'indexes': [models.Index(fields=['institution', 'image_status', 'sort_order'], name='portal_capt_institu_21ddf3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='schoolclass',
            constraint=models.UniqueConstraint(fields=('institution', 'slug'), name='uniq_class_slug'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school_class', 'sort_order'], name='portal_stud_school__e0fff8_idx'),
        ),
    ]
