# Generated by Django 5.2.17 on 2026-09-19 16:38

import django.db.models.deletion
from django.db import migrations, models


def backfill_workspaces(apps, schema_editor):
    """Every institution that already has caption items gets its workspace, and its items move into it."""
    CaptionItem = apps.get_model("portal", "CaptionItem")
    CaptionWorkspace = apps.get_model("portal", "CaptionWorkspace")
    for institution_id in CaptionItem.objects.values_list("institution_id", flat=True).distinct():
        workspace, _ = CaptionWorkspace.objects.get_or_create(institution_id=institution_id)
        CaptionItem.objects.filter(institution_id=institution_id, workspace__isnull=True).update(workspace=workspace)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captionitem',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Optional: the event this photo is from.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caption_items', to='catalog.event'),
        ),
        migrations.CreateModel(
            name='CaptionWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Internal notes, e.g. who to talk to at the institution.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caption_workspace', to='catalog.institution')),
            ],
            options={
                'verbose_name': 'caption workspace',
                'ordering': ['institution__name'],
            },
        ),
        migrations.AddField(
            model_name='captionitem',
            name='workspace',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portal.captionworkspace'),
        ),
        migrations.CreateModel(
            name='PortalAccessEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('note', models.CharField(blank=True, help_text='Who this is, e.g. "Principal" or "Class 6 coordinator".', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_emails', to='catalog.institution')),
            ],
            options={
                'verbose_name': 'portal access email',
                'ordering': ['institution__name', 'email'],
            },
        ),
        migrations.RunPython(backfill_workspaces, migrations.RunPython.noop),
    ]
