# Generated by Django 5.2.17 on 2026-10-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_caption_workspace_access_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="captionitem",
            name="action_by_phone",
            field=models.CharField(
                blank=True,
                help_text="Mobile number given alongside the name when the action was taken.",
                max_length=20,
                verbose_name="action by (phone)",
            ),
        ),
    ]
