# Generated by Django 5.2.17 on 2026-10-08 11:05

from django.db import migrations, models


def fold_corrections_into_captions(apps, schema_editor):
    """Corrections now rewrite the title in place, so a pending correction note
    becomes the item's text before the column is dropped."""
    CaptionItem = apps.get_model("portal", "CaptionItem")
    for item in CaptionItem.objects.exclude(correction="").only("pk", "correction"):
        CaptionItem.objects.filter(pk=item.pk).update(caption=item.correction)


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_captionitem_action_by_phone"),
    ]

    operations = [
        migrations.RunPython(fold_corrections_into_captions, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="captionitem",
            options={"ordering": ["sort_order", "pk"], "verbose_name": "title item"},
        ),
        migrations.AlterModelOptions(
            name="captionworkspace",
            options={
                "ordering": ["institution__name"],
                "verbose_name": "title workspace",
            },
        ),
        migrations.RemoveField(
            model_name="captionitem",
            name="correction",
        ),
        migrations.AddField(
            model_name="captionitem",
            name="source_name",
            field=models.CharField(
                blank=True, editable=False, max_length=200, verbose_name="file name"
            ),
        ),
        migrations.AlterField(
            model_name="captionitem",
            name="caption",
            field=models.TextField(blank=True, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="captionitem",
            name="requested",
            field=models.CharField(
                choices=[
                    ("needs-caption", "For Title"),
                    ("needs-correction", "For Correction"),
                    ("needs-approval", "For Approval"),
                ],
                default="needs-approval",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="captionitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("needs-caption", "For Title"),
                    ("needs-correction", "For Correction"),
                    ("needs-approval", "For Approval"),
                    ("approved", "Approved"),
                    ("corrected", "Corrected"),
                ],
                db_index=True,
                default="needs-approval",
                max_length=20,
            ),
        ),
    ]
