# Generated by Django 5.2.17 on 2026-10-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_alter_captionitem_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="captionitem",
            options={
                "ordering": ["sort_order", "pk"],
                "verbose_name": "class photograph item",
                "verbose_name_plural": "class photograph items",
            },
        ),
    ]
