# Generated by Django 5.2.17 on 2026-10-10 12:19

"""
"For Correction" is folded into "For Approval": approving already lets the
teacher adjust the wording, so a separate correction round isn't needed.

Photos still waiting for a correction become For Approval (their title and
everything else unchanged), and every photo that was *requested* as a
correction records For Approval as its request. Finished photos keep their
status (Approved / Submitted). Only the tag changes; no row is removed.
Reversing leaves the tags as they are: which ones were corrections can't be
told apart afterwards, and both are valid then.
"""

from django.db import migrations, models


def fold_corrections(apps, schema_editor):
    CaptionItem = apps.get_model("portal", "CaptionItem")
    waiting = CaptionItem.objects.filter(status="needs-correction").update(status="needs-approval")
    requested = CaptionItem.objects.filter(requested="needs-correction").update(requested="needs-approval")
    if waiting or requested:
        print(f"\n  For Correction -> For Approval: {waiting} waiting photo(s); {requested} request tag(s) updated.")


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_sign_in_on_each_access_email'),
    ]

    operations = [
        migrations.RunPython(fold_corrections, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='captionitem',
            name='requested',
            field=models.CharField(choices=[('needs-caption', 'For Title'), ('needs-approval', 'For Approval')], default='needs-approval', max_length=20),
        ),
        migrations.AlterField(
            model_name='captionitem',
            name='status',
            field=models.CharField(choices=[('needs-caption', 'For Title'), ('needs-approval', 'For Approval'), ('approved', 'Approved'), ('corrected', 'Submitted')], db_index=True, default='needs-approval', max_length=20),
        ),
    ]
