# Generated by Django 5.2.17 on 2026-10-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_fold_correction_into_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='comment',
            field=models.TextField(blank=True, help_text='Written by the institution on the website (Add Comments). The photo download puts it in the class folder as comment.txt.', verbose_name='comment from the institution'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_absentee',
            field=models.BooleanField(default=False, help_text='Added by the institution on the website (Add Absentees).', verbose_name='absentee'),
        ),
    ]
