# Generated by Django 5.2.17 on 2026-09-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalpage',
            name='download_pdf',
        ),
        migrations.RemoveField(
            model_name='portalpage',
            name='pdf_footer',
        ),
        migrations.RemoveField(
            model_name='portalpage',
            name='pdf_toast',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='intro_line_one',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='intro_line_two',
        ),
        migrations.AddField(
            model_name='eventspage',
            name='search_empty',
            field=models.CharField(blank=True, default="Nothing matches “{query}”. Try the institution's name or the event.", max_length=200),
        ),
        migrations.AddField(
            model_name='eventspage',
            name='search_placeholder',
            field=models.CharField(blank=True, default='Search events or institutions…', max_length=80),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='access_button',
            field=models.CharField(blank=True, default='Continue →', max_length=60),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='access_change',
            field=models.CharField(blank=True, default='Use a different email', max_length=60),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='access_error',
            field=models.CharField(blank=True, default="This email doesn't have workspace access yet. Contact support@spectrum.in.", max_length=200),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='access_eyebrow',
            field=models.CharField(blank=True, default='Institution Access', max_length=60),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='access_placeholder',
            field=models.CharField(blank=True, default='you@yourschool.edu', max_length=60),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='access_subtitle',
            field=models.TextField(blank=True, default='The workspace is open to institutions Spectrum works with. Use the email address registered with us.'),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='access_title',
            field=models.CharField(blank=True, default='Enter your institution email', max_length=200),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='download_note',
            field=models.CharField(blank=True, default='Only named students are included — {count} still unnamed.', max_length=200),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='download_photos',
            field=models.CharField(blank=True, default='Download Class Photos →', max_length=60),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='download_toast',
            field=models.CharField(blank=True, default='{count} photos downloaded', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_portal',
            field=models.CharField(blank=True, default='Portal', help_text='Only shown to visitors who have unlocked the institution portal.', max_length=40),
        ),
    ]
