# Generated by Django 5.2.17 on 2026-09-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_portal_access_search_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_portal_link',
            field=models.CharField(blank=True, default='Institution Login', help_text="Footer link to the portal's email step.", max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_home',
            field=models.CharField(blank=True, default='Home', help_text='Used in the footer; the navbar shows the logo instead.', max_length=40),
        ),
    ]
