# Generated by Django 5.2.17 on 2026-09-19 17:16

from django.db import migrations, models


def relabel_untouched_nav_portal(apps, schema_editor):
    """
    Changing a field's default leaves existing rows alone, so move the saved
    label too — but only where it is still the old default. A label the admin
    has already edited is theirs and is left as it is.
    """
    SiteSettings = apps.get_model("content", "SiteSettings")
    SiteSettings.objects.filter(nav_portal="Portal").update(nav_portal="Institution")


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_nav_home_footer_portal_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_portal',
            field=models.CharField(blank=True, default='Institution', help_text='Only shown to visitors who have unlocked the institution portal.', max_length=40),
        ),
        migrations.RunPython(relabel_untouched_nav_portal, migrations.RunPython.noop),
    ]
