# Generated by Django 5.2.17 on 2026-09-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_rename_nav_portal_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalpage',
            name='guidelines_dismiss',
            field=models.CharField(blank=True, default='Got it', max_length=40),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='guidelines_intro',
            field=models.TextField(blank=True, default='Captions travel with every photo we deliver, so a little care here saves a round of corrections later. Please read these before you write or approve a caption.'),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='guidelines_link',
            field=models.CharField(blank=True, default='View guidelines', max_length=60),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='guidelines_outro',
            field=models.TextField(blank=True, default='Approved captions are locked, so take a moment before you approve.'),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='guidelines_points',
            field=models.TextField(blank=True, default='Write one clear sentence per photo: who is in it, what is happening, and where or when.\nUse full names and correct titles for staff and guests, exactly as the institution spells them.\nCheck spellings of student names against the class register before approving.\nKeep to plain, present-tense language; avoid slang and abbreviations.\nIf a caption is wrong, describe what should change rather than rewriting it from scratch.', help_text='One pointer per line.'),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='guidelines_prompt',
            field=models.CharField(blank=True, default='Please follow the guidelines', help_text='Shown beside the status tag in the editor.', max_length=80),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='guidelines_title',
            field=models.CharField(blank=True, default='Caption Guidelines', max_length=200),
        ),
    ]
