# Generated by Django 5.2.17 on 2026-09-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_caption_guidelines'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalpage',
            name='idcards_card_badge',
            field=models.CharField(blank=True, default='Coming soon', max_length=40),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='idcards_card_copy',
            field=models.CharField(blank=True, default='Design, proof and order student ID cards from the class photos.', max_length=200),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='idcards_card_title',
            field=models.CharField(blank=True, default='ID Cards', max_length=60),
        ),
    ]
