# Generated by Django 5.2.17 on 2026-09-20 02:52

from django.db import migrations, models


def relabel_untouched_subtitle(apps, schema_editor):
    """Move the saved line too, but only where it is still the old default."""
    SiteSettings = apps.get_model("content", "PortalPage")
    SiteSettings.objects.filter(workspace_subtitle="Two workspaces, one institution account.").update(
        workspace_subtitle="One institution account, everything in one place.")


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_idcards_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalpage',
            name='workspace_subtitle',
            field=models.CharField(blank=True, default='One institution account, everything in one place.', max_length=200),
        ),
        migrations.RunPython(relabel_untouched_subtitle, migrations.RunPython.noop),
    ]
