# Generated by Django 6.0.6 on 2026-10-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_remove_type_filter_copy"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallerypage",
            name="selection_mixed",
            field=models.CharField(
                blank=True,
                default="{photos} photos + {videos} videos · ₹{price}",
                help_text="Shown when the selection includes videos.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="videos_heading",
            field=models.CharField(
                blank=True,
                default="Event Videos",
                help_text="Heading above the videos; hidden when an event has none.",
                max_length=80,
            ),
        ),
    ]
