# Generated by Django 6.0.6 on 2026-10-04 03:00

from django.db import migrations, models


def relabel_untouched_search(apps, schema_editor):
    """The search bar became a button; move the label too unless the admin edited it."""
    HomePage = apps.get_model("content", "HomePage")
    HomePage.objects.filter(search_placeholder="Find your school, college, or event\u2026").update(
        search_placeholder="Click here to browse institutions\u2026")

    from apps.core.cache import bump
    bump()


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_gallerypage_selection_mixed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="ticker_heading",
            field=models.CharField(
                blank=True,
                default="Our [Story]",
                help_text="Wrap words in [brackets] to show them in the Spectrum gradient.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="ticker_text",
            field=models.TextField(
                blank=True,
                default="In 1980, a single camera and a belief: every institution's moments deserve to be kept beautifully.\nWe began in the darkrooms of Delhi, printing school annual days frame by frame.\nFilm gave way to digital; our standards never did.\nFour decades on, the same families recognise us at the school gate.\nEvery event we cover is edited, curated and delivered entirely in-house.\nBecause a photograph is not a file — it is the day itself, kept safe.\nSpectrum — imagination that works, since 1980.",
                help_text="The slowly rising story above the tie-ups. Each line scrolls past on its own; wrap words in [brackets] for the gradient.",
            ),
        ),
        migrations.AddField(
            model_name="eventspage",
            name="browse_events_template",
            field=models.CharField(
                blank=True,
                default="{count} events",
                help_text="Under each icon; {count} is the event count.",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="eventspage",
            name="browse_subtitle",
            field=models.TextField(
                blank=True,
                default="Pick your school or college to see every event we've covered there.",
            ),
        ),
        migrations.AddField(
            model_name="eventspage",
            name="browse_title",
            field=models.CharField(
                blank=True,
                default="Choose Your [Institution]",
                help_text="Wrap words in [brackets] to show them in the Spectrum gradient.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="search_placeholder",
            field=models.CharField(
                blank=True,
                default="Click here to browse institutions…",
                help_text="Label on the search-bar-styled button that opens the institutions page.",
                max_length=200,
            ),
        ),
        migrations.RunPython(relabel_untouched_search, migrations.RunPython.noop),
    ]
