# Generated by Django 6.0.6 on 2026-10-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_aboutpage_ticker_heading_aboutpage_ticker_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallerypage",
            name="download_all",
        ),
        migrations.RemoveField(
            model_name="gallerypage",
            name="download_missing",
        ),
        migrations.RemoveField(
            model_name="gallerypage",
            name="download_one",
        ),
        migrations.RemoveField(
            model_name="gallerypage",
            name="download_subtitle",
        ),
        migrations.RemoveField(
            model_name="gallerypage",
            name="download_title",
        ),
        migrations.RemoveField(
            model_name="gallerypage",
            name="success_download",
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="filter_photos",
            field=models.CharField(
                blank=True,
                default="Photos",
                help_text="Gallery filter chip; shown when the event has videos.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="filter_videos",
            field=models.CharField(blank=True, default="Videos", max_length=40),
        ),
    ]
