# Generated by Django 6.0.6 on 2026-10-04 11:58

import apps.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_remove_gallerypage_download_all_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="intro_audio",
            field=models.FileField(
                blank=True,
                help_text="Plays with the brand intro. Browsers only allow sound after the visitor has interacted, so it may start on their first tap/click.",
                upload_to=apps.content.models.site_upload,
                verbose_name="intro sound (MP3)",
            ),
        ),
    ]
