# Generated by Django 6.0.6 on 2026-10-04 13:18

import apps.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0013_sitesettings_intro_audio"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="session_audio",
            field=models.FileField(
                blank=True,
                help_text="Soft loop that plays through the visit, starting a beat after the intro. Visitors can mute it from the navbar.",
                upload_to=apps.content.models.site_upload,
                verbose_name="background music (MP3)",
            ),
        ),
    ]
