# Generated by Django 6.0.6 on 2026-10-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0014_sitesettings_session_audio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallerypage",
            name="deliver_via",
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="contact_required",
            field=models.CharField(
                blank=True,
                default="Add a WhatsApp number or email address so we can deliver your memories.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="email_hint",
            field=models.CharField(
                blank=True,
                default="Add, if you want photographs on email",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="whatsapp_hint",
            field=models.CharField(
                blank=True,
                default="Add, if you want photographs on WhatsApp",
                max_length=200,
            ),
        ),
    ]
