# Generated by Django 6.0.6 on 2026-10-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0015_remove_gallerypage_deliver_via_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutpage",
            name="tieup_years_template",
        ),
        migrations.RemoveField(
            model_name="tieup",
            name="years",
        ),
        migrations.AddField(
            model_name="tieup",
            name="note",
            field=models.CharField(
                blank=True,
                help_text='Shown as written, e.g. "Tied up for 15+ years". Blank shows nothing.',
                max_length=120,
                verbose_name="line under the name",
            ),
        ),
    ]
