# Generated by Django 5.2.17 on 2026-10-06 10:34

from django.db import migrations, models

# The caption -> title / Events -> Class Photographs / Students -> Individual
# Photographs renames. Saved rows are moved too, but only where the text is
# still the old default, so hand-edited copy is never overwritten.
RELABELS = {
    "captions_title": ("Caption Workspace", "Title Workspace"),
    "events_card_title": ("Events", "Class Photographs"),
    "events_card_copy": (
        "Review and correct photo captions for event moments.",
        "Review and correct photo titles for event moments.",
    ),
    "students_card_title": ("Students", "Individual Photographs"),
    "guidelines_title": ("Caption Guidelines", "Title Guidelines"),
    "guidelines_intro": (
        "Captions travel with every photo we deliver, so a little care here saves a round of corrections "
        "later. Please read these before you write or approve a caption.",
        "Titles travel with every photo we deliver, so a little care here saves a round of corrections "
        "later. Please read these before you write or approve a title.",
    ),
    "guidelines_points": (
        "Write one clear sentence per photo: who is in it, what is happening, and where or when.\n"
        "Use full names and correct titles for staff and guests, exactly as the institution spells them.\n"
        "Check spellings of student names against the class register before approving.\n"
        "Keep to plain, present-tense language; avoid slang and abbreviations.\n"
        "If a caption is wrong, describe what should change rather than rewriting it from scratch.",
        "Write one clear sentence per photo: who is in it, what is happening, and where or when.\n"
        "Use full names and correct titles for staff and guests, exactly as the institution spells them.\n"
        "Check spellings of student names against the class register before approving.\n"
        "Keep to plain, present-tense language; avoid slang and abbreviations.\n"
        "If a title is wrong, describe what should change rather than rewriting it from scratch.",
    ),
    "guidelines_outro": (
        "Approved captions are locked, so take a moment before you approve.",
        "Approved titles are locked, so take a moment before you approve.",
    ),
    "locked_body": (
        "This caption is approved and can no longer be edited.",
        "This title is approved and can no longer be edited.",
    ),
}


def relabel_untouched_copy(apps, schema_editor):
    PortalPage = apps.get_model("content", "PortalPage")
    for field, (old, new) in RELABELS.items():
        PortalPage.objects.filter(**{field: old}).update(**{field: new})


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0016_remove_aboutpage_tieup_years_template_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portalpage",
            name="captions_title",
            field=models.CharField(
                blank=True, default="Title Workspace", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="portalpage",
            name="events_card_copy",
            field=models.CharField(
                blank=True,
                default="Review and correct photo titles for event moments.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="portalpage",
            name="events_card_title",
            field=models.CharField(
                blank=True, default="Class Photographs", max_length=60
            ),
        ),
        migrations.AlterField(
            model_name="portalpage",
            name="guidelines_intro",
            field=models.TextField(
                blank=True,
                default="Titles travel with every photo we deliver, so a little care here saves a round of corrections later. Please read these before you write or approve a title.",
            ),
        ),
        migrations.AlterField(
            model_name="portalpage",
            name="guidelines_outro",
            field=models.TextField(
                blank=True,
                default="Approved titles are locked, so take a moment before you approve.",
            ),
        ),
        migrations.AlterField(
            model_name="portalpage",
            name="guidelines_points",
            field=models.TextField(
                blank=True,
                default="Write one clear sentence per photo: who is in it, what is happening, and where or when.\nUse full names and correct titles for staff and guests, exactly as the institution spells them.\nCheck spellings of student names against the class register before approving.\nKeep to plain, present-tense language; avoid slang and abbreviations.\nIf a title is wrong, describe what should change rather than rewriting it from scratch.",
                help_text="One pointer per line.",
            ),
        ),
        migrations.AlterField(
            model_name="portalpage",
            name="guidelines_title",
            field=models.CharField(
                blank=True, default="Title Guidelines", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="portalpage",
            name="locked_body",
            field=models.CharField(
                blank=True,
                default="This title is approved and can no longer be edited.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="portalpage",
            name="students_card_title",
            field=models.CharField(
                blank=True, default="Individual Photographs", max_length=60
            ),
        ),
        migrations.RunPython(relabel_untouched_copy, migrations.RunPython.noop),
    ]
