# Generated by Django 5.2.17 on 2026-10-08 11:05

from django.db import migrations, models

OLD_LAST_LINE = "If a title is wrong, describe what should change rather than rewriting it from scratch."
NEW_LAST_LINE = "If a title is wrong, write the corrected title in its place."


def relabel_untouched_points(apps, schema_editor):
    """Corrections now rewrite the title, so the pointer saying otherwise moves
    too — but only where the saved line is still the old default."""
    PortalPage = apps.get_model("content", "PortalPage")
    for page in PortalPage.objects.all():
        if OLD_LAST_LINE in page.guidelines_points:
            PortalPage.objects.filter(pk=page.pk).update(
                guidelines_points=page.guidelines_points.replace(OLD_LAST_LINE, NEW_LAST_LINE))
    from apps.core.cache import bump

    bump()


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0017_alter_portalpage_captions_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portalpage",
            name="guidelines_points",
            field=models.TextField(
                blank=True,
                default="Write one clear sentence per photo: who is in it, what is happening, and where or when.\nUse full names and correct titles for staff and guests, exactly as the institution spells them.\nCheck spellings of student names against the class register before approving.\nKeep to plain, present-tense language; avoid slang and abbreviations.\nIf a title is wrong, write the corrected title in its place.",
                help_text="One pointer per line.",
            ),
        ),
        migrations.RunPython(relabel_untouched_points, migrations.RunPython.noop),
    ]
