# Generated by Django 5.2.17 on 2026-10-08 11:19

from django.db import migrations, models

# Saving now locks an item too, so the overlay can no longer claim "approved".
# Rows still holding either earlier default move along; edited copy is kept.
OLD_DEFAULTS = (
    "This title is approved and can no longer be edited.",
    "This caption is approved and can no longer be edited.",
)
NEW_DEFAULT = "This title has been submitted and locked. Only the Spectrum team can change it now."


def relabel_untouched_locked_body(apps, schema_editor):
    PortalPage = apps.get_model("content", "PortalPage")
    PortalPage.objects.filter(locked_body__in=OLD_DEFAULTS).update(locked_body=NEW_DEFAULT)
    from apps.core.cache import bump

    bump()


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0018_alter_portalpage_guidelines_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portalpage",
            name="locked_body",
            field=models.CharField(
                blank=True,
                default="This title has been submitted and locked. Only the Spectrum team can change it now.",
                max_length=200,
            ),
        ),
        migrations.RunPython(relabel_untouched_locked_body, migrations.RunPython.noop),
    ]
