# Generated by Django 5.2.17 on 2026-10-08 12:34

from django.db import migrations


def refresh_cache(apps, schema_editor):
    """Schema-only changes skip the versioning signal; the serialized portal
    copy must stop carrying the removed download lines."""
    from apps.core.cache import bump

    bump()


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0019_alter_portalpage_locked_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portalpage",
            name="download_note",
        ),
        migrations.RemoveField(
            model_name="portalpage",
            name="download_photos",
        ),
        migrations.RemoveField(
            model_name="portalpage",
            name="download_toast",
        ),
        migrations.RunPython(refresh_cache, migrations.RunPython.noop),
    ]
