# Generated by Django 5.2.17 on 2026-10-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_remove_portalpage_download_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portalpage',
            options={'verbose_name': 'institution portal page', 'verbose_name_plural': 'institution portal pages'},
        ),
    ]
