# Generated by Django 5.2.17 on 2026-10-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_portal_page_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalpage',
            name='captions_empty_submitted',
            field=models.CharField(blank=True, default='Nothing submitted yet.', max_length=200),
        ),
    ]
