# Generated by Django 5.2.17 on 2026-10-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_captions_empty_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypage',
            name='not_for_sale_message',
            field=models.TextField(blank=True, default='These photographs are not available for sale. Please contact your Institute’s management.', help_text='Shown in place of the checkout for events marked Not for sale.'),
        ),
    ]
