# Generated by Django 5.2.17 on 2026-10-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_not_for_sale_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalpage',
            name='roster_guidelines_dismiss',
            field=models.CharField(blank=True, default='Got it', max_length=40),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='roster_guidelines_intro',
            field=models.TextField(blank=True, default='Student names travel with every photo we deliver, so please read these before you name the students.'),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='roster_guidelines_link',
            field=models.CharField(blank=True, default='View guidelines', max_length=60),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='roster_guidelines_outro',
            field=models.TextField(blank=True, default='Names go on the photos we deliver, so take a moment to check them.'),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='roster_guidelines_points',
            field=models.TextField(blank=True, default="Type each student's full name exactly as it appears in the class register.\nCheck the spelling before moving on — Enter saves the name and jumps to the next photo.\nLeave a photo blank if you can't identify the student; please don't guess.\nUse Add Absentees for students missing from the class photos, then name them like the rest.\nUse Add Comments to tell the Spectrum team anything about this class.", help_text='One pointer per line.'),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='roster_guidelines_title',
            field=models.CharField(blank=True, default='Naming Guidelines', max_length=200),
        ),
    ]
