# Generated by Django 5.2.17 on 2026-09-16 19:14

import apps.orders.models
import django.db.models.deletion
import spectrum.storages
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=apps.orders.models.public_id, editable=False, max_length=12, unique=True, verbose_name='order no.')),
                ('kind', models.CharField(choices=[('photos', 'Selected photos'), ('bundle', 'Full album')], max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('deliver_whatsapp', models.BooleanField(default=True)),
                ('deliver_email', models.BooleanField(default=False)),
                ('amount_paise', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Awaiting payment'), ('paid', 'Paid'), ('failed', 'Payment failed'), ('delivered', 'Delivered'), ('refunded', 'Refunded')], db_index=True, default='created', max_length=10)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('download_token', models.CharField(default=apps.orders.models.download_token, editable=False, max_length=64, unique=True)),
                ('zip_file', models.FileField(blank=True, editable=False, max_length=255, storage=spectrum.storages.private_storage, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_payment_id', models.CharField(max_length=40, unique=True)),
                ('method', models.CharField(blank=True, max_length=30)),
                ('amount_paise', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='captured', max_length=20)),
                ('verified_via', models.CharField(choices=[('client', 'Checkout'), ('webhook', 'Webhook'), ('mock', 'Test mode')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('event_id', models.CharField(max_length=80)),
                ('event_type', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='uniq_webhook_event')],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'deliveries',
                'constraints': [models.UniqueConstraint(fields=('order', 'channel'), name='uniq_delivery_channel')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price_paise', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.eventphoto')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order', 'photo'), name='uniq_order_photo')],
            },
        ),
    ]
