# Generated by Django 6.0.6 on 2026-10-03 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_event_price_per_video_alter_event_bundle_price_and_more"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="catalog.eventvideo",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="catalog.eventphoto",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "video"), name="uniq_order_video"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("photo__isnull", False), ("video__isnull", True)),
                    models.Q(("photo__isnull", True), ("video__isnull", False)),
                    _connector="OR",
                ),
                name="orderitem_photo_or_video",
            ),
        ),
    ]
