# Generated by Django 6.0.6 on 2026-10-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderitem_video_alter_orderitem_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="video_used_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Video links are one-time; set when the download is taken.",
                null=True,
            ),
        ),
    ]
