/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as EventsSlugRouteImport } from './routes/events/$slug'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalWorkspaceIndexRouteImport } from './routes/portal.workspace.index'
import { Route as PortalWorkspaceEventsRouteImport } from './routes/portal.workspace.events'
import { Route as PortalWorkspaceStudentsIndexRouteImport } from './routes/portal.workspace.students.index'
import { Route as PortalWorkspaceStudentsClassIdRouteImport } from './routes/portal.workspace.students.$classId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalWorkspaceIndexRoute = PortalWorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalWorkspaceEventsRoute = PortalWorkspaceEventsRouteImport.update({
  id: '/workspace/events',
  path: '/workspace/events',
  getParentRoute: () => PortalRoute,
} as any)
const PortalWorkspaceStudentsIndexRoute =
  PortalWorkspaceStudentsIndexRouteImport.update({
    id: '/workspace/students/',
    path: '/workspace/students/',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalWorkspaceStudentsClassIdRoute =
  PortalWorkspaceStudentsClassIdRouteImport.update({
    id: '/workspace/students/$classId',
    path: '/workspace/students/$classId',
    getParentRoute: () => PortalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/portal': typeof PortalRouteWithChildren
  '/events/$slug': typeof EventsSlugRoute
  '/events/': typeof EventsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/workspace/events': typeof PortalWorkspaceEventsRoute
  '/portal/workspace/': typeof PortalWorkspaceIndexRoute
  '/portal/workspace/students/$classId': typeof PortalWorkspaceStudentsClassIdRoute
  '/portal/workspace/students/': typeof PortalWorkspaceStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events': typeof EventsIndexRoute
  '/portal': typeof PortalIndexRoute
  '/portal/workspace/events': typeof PortalWorkspaceEventsRoute
  '/portal/workspace': typeof PortalWorkspaceIndexRoute
  '/portal/workspace/students/$classId': typeof PortalWorkspaceStudentsClassIdRoute
  '/portal/workspace/students': typeof PortalWorkspaceStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/portal': typeof PortalRouteWithChildren
  '/events/$slug': typeof EventsSlugRoute
  '/events/': typeof EventsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/workspace/events': typeof PortalWorkspaceEventsRoute
  '/portal/workspace/': typeof PortalWorkspaceIndexRoute
  '/portal/workspace/students/$classId': typeof PortalWorkspaceStudentsClassIdRoute
  '/portal/workspace/students/': typeof PortalWorkspaceStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/how-it-works'
    | '/portal'
    | '/events/$slug'
    | '/events/'
    | '/portal/'
    | '/portal/workspace/events'
    | '/portal/workspace/'
    | '/portal/workspace/students/$classId'
    | '/portal/workspace/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/how-it-works'
    | '/events/$slug'
    | '/events'
    | '/portal'
    | '/portal/workspace/events'
    | '/portal/workspace'
    | '/portal/workspace/students/$classId'
    | '/portal/workspace/students'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/how-it-works'
    | '/portal'
    | '/events/$slug'
    | '/events/'
    | '/portal/'
    | '/portal/workspace/events'
    | '/portal/workspace/'
    | '/portal/workspace/students/$classId'
    | '/portal/workspace/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PortalRoute: typeof PortalRouteWithChildren
  EventsSlugRoute: typeof EventsSlugRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/workspace/': {
      id: '/portal/workspace/'
      path: '/workspace'
      fullPath: '/portal/workspace/'
      preLoaderRoute: typeof PortalWorkspaceIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/workspace/events': {
      id: '/portal/workspace/events'
      path: '/workspace/events'
      fullPath: '/portal/workspace/events'
      preLoaderRoute: typeof PortalWorkspaceEventsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/workspace/students/': {
      id: '/portal/workspace/students/'
      path: '/workspace/students'
      fullPath: '/portal/workspace/students/'
      preLoaderRoute: typeof PortalWorkspaceStudentsIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/workspace/students/$classId': {
      id: '/portal/workspace/students/$classId'
      path: '/workspace/students/$classId'
      fullPath: '/portal/workspace/students/$classId'
      preLoaderRoute: typeof PortalWorkspaceStudentsClassIdRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalIndexRoute: typeof PortalIndexRoute
  PortalWorkspaceEventsRoute: typeof PortalWorkspaceEventsRoute
  PortalWorkspaceIndexRoute: typeof PortalWorkspaceIndexRoute
  PortalWorkspaceStudentsClassIdRoute: typeof PortalWorkspaceStudentsClassIdRoute
  PortalWorkspaceStudentsIndexRoute: typeof PortalWorkspaceStudentsIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalIndexRoute: PortalIndexRoute,
  PortalWorkspaceEventsRoute: PortalWorkspaceEventsRoute,
  PortalWorkspaceIndexRoute: PortalWorkspaceIndexRoute,
  PortalWorkspaceStudentsClassIdRoute: PortalWorkspaceStudentsClassIdRoute,
  PortalWorkspaceStudentsIndexRoute: PortalWorkspaceStudentsIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HowItWorksRoute: HowItWorksRoute,
  PortalRoute: PortalRouteWithChildren,
  EventsSlugRoute: EventsSlugRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
